vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: '%app.path.images%'
            upload_destination: '%kernel.project_dir%/public%app.path.images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
        performers:
            uri_prefix: '%app.path.images%performers'
            upload_destination: '%kernel.project_dir%/public%app.path.images%performers'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true